services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: invest
      POSTGRES_PASSWORD: investpw
      POSTGRES_DB: investdb
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7

  backend:
    build: ./backend
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: postgresql+asyncpg://invest:investpw@db/investdb
      REDIS_URL: redis://redis:6379/0

  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - "3000:3000"

volumes:
  db_data:
